### ISSUE TITLE
CLI: Create post-process command

### ISSUE THREAD

**Issue by marcelometal** [olhoneles/politicos-go#3]
Please, don't repeat yourself!

Today there are these CLI commands:
* post-process-candidacies-status
* post-process-education
* post-process-political-office
* post-process-political-party

But we could create `post-process` command and using `candidacies-status`, `education`,  `political-office` and `political-party` as arg value

**Comment by luccamendonca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create post-process command](https://trello.com/c/6Afn5wkq/44-create-post-process-command)
